version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "0.0.0.0:81:80"
    volumes:
      - media_files:/app/media:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app_net
    environment:
      - TZ=Africa/Cairo

  frontend:
    build:
      context: .
      dockerfile:
           frontend/Dockerfile
      args:
        - VITE_API_URL=/api/v1
    environment:
      - TZ=Africa/Cairo
    restart: unless-stopped
    networks:
      - app_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      POSTGRESQL_HOST: ${DB_HOST}
      POSTGRESQL_PORT: ${DB_PORT}
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
      MEDIA_ROOT: ${MEDIA_ROOT}
      JOB_ORDER_IMAGE_UPLOAD_DIR: ${MEDIA_ROOT}
      REPORTS_DIR: ${REPORTS_ROOT}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      TZ: Africa/Cairo
      CUPS_SERVER: /var/run/cups/cups.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_files:/app/media
      - reports:/app/reports
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  report-email-worker:
    build:
      context: ./report-email-worker
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      API_BASE_URL: http://192.168.0.249:8000/api/v1
      TZ: Africa/Cairo
    networks:
      - app_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  app_net:
    driver: bridge

volumes:
  media_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/appdata/media
  reports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/appdata/reports
