"""One-shot: login, download three daily PDFs, email them."""

from __future__ import annotations

import argparse
import logging
import os
import sys
from datetime import date
from typing import Optional

from api_client import ReportApiClient
from config import load_settings
from mailer import send_report_bundle


def _load_dotenv_if_present() -> None:
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    if not os.path.isfile(env_path):
        return
    with open(env_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                k, v = k.strip(), v.strip().strip('"').strip("'")
                if k and k not in os.environ:
                    os.environ[k] = v


def _html_body(company_name: str, report_date: date) -> str:
    ds = report_date.isoformat()
    return f"""\
<html><body>
<p>Daily production reports for <strong>{ds}</strong>.</p>
<p>{company_name}</p>
<p><i>Generated by the report email worker.</i></p>
</body></html>"""


def run_job(report_date_override: Optional[date] = None) -> None:
    """Download PDFs via API and send one email with attachments."""
    settings = load_settings()
    report_date = report_date_override if report_date_override is not None else settings.report_date()

    client = ReportApiClient(
        settings.api_base_url,
        settings.username,
        settings.password,
    )
    token = client.login()
    attachments = client.download_daily_reports(token, report_date)

    subject = f"Daily production reports — {report_date.isoformat()}"
    body = _html_body(settings.company_name, report_date)
    send_report_bundle(
        smtp_host=settings.smtp_host,
        smtp_port=settings.smtp_port,
        smtp_use_tls=settings.smtp_use_tls,
        sender_email=settings.sender_email,
        sender_password=settings.sender_password,
        recipient_emails=settings.recipient_emails,
        subject=subject,
        html_body=body,
        attachments=attachments,
    )


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    _load_dotenv_if_present()

    parser = argparse.ArgumentParser(description="Fetch daily PDF reports and email them.")
    parser.add_argument(
        "--date",
        help="Report date YYYY-MM-DD (overrides REPORT_DATE_MODE)",
    )
    args = parser.parse_args()

    settings = load_settings()
    if args.date:
        report_date = date.fromisoformat(args.date)
    else:
        report_date = settings.report_date()

    run_job(report_date)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as e:
        logging.exception("%s", e)
        sys.exit(1)
